"""
Traffic Classifier Module.
Distinguishes between Complexity Attacks, Benign Traffic Surges, Downstream Stalls, and Normal baseline.

HONESTY NOTICE:
This classifier is a lightweight, rule-based heuristic decision engine tuned against
synthetic attack and traffic profiles generated by our load simulator. It is not deep learning
and is not trained on real-world attack datasets.
"""
from enum import Enum
from typing import Dict, Any
from backend.config import config

class TrafficClassification(str, Enum):
    NORMAL = "NORMAL"
    BENIGN_SURGE = "BENIGN_SURGE"
    COMPLEXITY_ATTACK = "COMPLEXITY_ATTACK"
    DOWNSTREAM_STALL = "DOWNSTREAM_STALL"

class TrafficClassifier:
    def __init__(self):
        pass

    def classify(self, metrics: Dict[str, Any]) -> Dict[str, Any]:
        """
        Evaluates real-time telemetry metrics and determines the traffic state.
        
        Decision Factors:
        1. cpu_load: System CPU % and mean per-request CPU time.
        2. concentration: Ratio of traffic hitting /verify-crypto vs other endpoints.
        3. latency_slope: Degradation rate of response time (ms/sec).
        4. rps: Total requests per second.
        """
        rps = metrics.get("rps", 0.0)
        crypto_concentration = metrics.get("crypto_concentration", 0.0)
        cpu_pct = metrics.get("system_cpu_percent", 0.0)
        mean_cpu_time = metrics.get("mean_cpu_time_ms", 0.0)
        mean_latency = metrics.get("mean_latency_ms", 0.0)
        latency_slope = metrics.get("latency_slope", 0.0)
        crypto_rps = metrics.get("crypto_rps", 0.0)

        # Baseline: If traffic is minimal, system is NORMAL
        if rps < 4.0 and mean_latency < 50.0 and cpu_pct < 40.0:
            return {
                "classification": TrafficClassification.NORMAL,
                "confidence": 0.95,
                "rationale": "Traffic volume and CPU utilization within baseline parameters.",
                "indicators": {
                    "cpu_stress": "Low",
                    "traffic_pattern": "Normal",
                    "threat_level": "None"
                }
            }

        # 1. Complexity Attack Signal:
        # High CPU stress (either system CPU > threshold OR mean CPU time per request > 10ms),
        # heavy concentration (>70%) on the expensive /verify-crypto endpoint,
        # or steep positive latency degradation slope.
        is_high_cpu = (cpu_pct >= config.ATTACK_CPU_THRESHOLD_PCT) or (mean_cpu_time >= 10.0 and crypto_rps >= 8.0)
        is_concentrated = crypto_concentration >= config.ATTACK_CRYPTO_CONCENTRATION
        is_degrading = latency_slope > config.ATTACK_LATENCY_GROWTH_SLOPE or mean_latency > 150.0

        if (is_high_cpu and is_concentrated) or (is_concentrated and is_degrading and crypto_rps >= 6.0):
            return {
                "classification": TrafficClassification.COMPLEXITY_ATTACK,
                "confidence": 0.92,
                "rationale": f"High CPU consumption ({cpu_pct}% / {mean_cpu_time}ms per req) concentrated on /verify-crypto ({round(crypto_concentration*100, 1)}% share) causing steep latency degradation ({round(latency_slope, 2)} ms/s).",
                "indicators": {
                    "cpu_stress": "Critical",
                    "traffic_pattern": "Concentrated Crypto Flood",
                    "threat_level": "High"
                }
            }

        # 2. Benign Traffic Surge Signal:
        # High RPS, but load is distributed across endpoints (concentration <= 45%),
        # CPU is distributed, latency remains manageable without explosive slope.
        if rps >= config.SURGE_MIN_RPS and crypto_concentration <= config.SURGE_MAX_CRYPTO_CONCENTRATION:
            return {
                "classification": TrafficClassification.BENIGN_SURGE,
                "confidence": 0.88,
                "rationale": f"High aggregate request rate ({rps} RPS) evenly distributed across endpoints ({round(crypto_concentration*100, 1)}% crypto share). CPU and latency within sustainable limits.",
                "indicators": {
                    "cpu_stress": "Moderate/Sustainable",
                    "traffic_pattern": "Distributed Surge",
                    "threat_level": "None (Legitimate)"
                }
            }

        # 3. Downstream / DB Stall Signal:
        # Latency is high or growing, but CPU is completely flat / low.
        if mean_latency > 200.0 and cpu_pct < 35.0 and mean_cpu_time < 3.0:
            return {
                "classification": TrafficClassification.DOWNSTREAM_STALL,
                "confidence": 0.85,
                "rationale": f"Elevated latency ({mean_latency} ms) with low CPU utilization ({cpu_pct}%). Indicates downstream I/O bottleneck, not algorithmic complexity exhaustion.",
                "indicators": {
                    "cpu_stress": "Low",
                    "traffic_pattern": "I/O Bound Stall",
                    "threat_level": "Internal Bottleneck"
                }
            }

        # Default fallback: Normal or mild load
        return {
            "classification": TrafficClassification.NORMAL,
            "confidence": 0.80,
            "rationale": f"System operating within normal operating envelopes (RPS: {rps}, CPU: {cpu_pct}%).",
            "indicators": {
                "cpu_stress": "Nominal",
                "traffic_pattern": "Balanced",
                "threat_level": "None"
            }
        }

classifier = TrafficClassifier()
